all: *.py *.txt
	python pb$(PROG).py < pb$(PROG).txt

create:
	touch pb$(PROG).py
	echo "# Code created by Romain Fouilland for problem:\n# \n" > pb$(PROG).py
	echo "n = int(input())\n\nfor _ in range(n):\n\t" >> pb$(PROG).py
	touch pb$(PROG).txt
